### ISSUE TITLE
Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by vitalijzad** [jhades/jhades#1]
My Java version is:
        java version "1.6.0_37"
       Java(TM) SE Runtime Environment (build 1.6.0_37-b06)
       Java HotSpot(TM) 64-Bit Server VM (build 20.12-b01, mixed mode)

I get the following stacktrace:

    java.lang.UnsupportedClassVersionError: org/jhades/standalone/JHadesStandaloneReport :Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: org.jhades.standalone.JHadesStandaloneReport. Program will exit.
Exception in thread "main"

**Comment by jhades** [comment]
This is because jHades needs Java 7
